// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD4ByBozhs5Wgq9sBLLWcibc1ewKggBZA',
    appId: '1:653228448901:web:79849a18acb0cfb02e1dec',
    messagingSenderId: '653228448901',
    projectId: 'doroteaapp-6c5cb',
    authDomain: 'doroteaapp-6c5cb.firebaseapp.com',
    storageBucket: 'doroteaapp-6c5cb.firebasestorage.app',
    measurementId: 'G-1GB3809VDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPl0OyUeUIceyCElYl9YD2Wnt-ZkO3dSg',
    appId: '1:653228448901:android:e1cb2f1b2d532e312e1dec',
    messagingSenderId: '653228448901',
    projectId: 'doroteaapp-6c5cb',
    storageBucket: 'doroteaapp-6c5cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQxUpgUj_vfm4QxtCeXGzRcoKY0dKkI6o',
    appId: '1:653228448901:ios:ca3c07dd81db96922e1dec',
    messagingSenderId: '653228448901',
    projectId: 'doroteaapp-6c5cb',
    storageBucket: 'doroteaapp-6c5cb.firebasestorage.app',
    iosBundleId: 'com.example.doroteaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQxUpgUj_vfm4QxtCeXGzRcoKY0dKkI6o',
    appId: '1:653228448901:ios:ca3c07dd81db96922e1dec',
    messagingSenderId: '653228448901',
    projectId: 'doroteaapp-6c5cb',
    storageBucket: 'doroteaapp-6c5cb.firebasestorage.app',
    iosBundleId: 'com.example.doroteaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD4ByBozhs5Wgq9sBLLWcibc1ewKggBZA',
    appId: '1:653228448901:web:d4cd87017b3fed0f2e1dec',
    messagingSenderId: '653228448901',
    projectId: 'doroteaapp-6c5cb',
    authDomain: 'doroteaapp-6c5cb.firebaseapp.com',
    storageBucket: 'doroteaapp-6c5cb.firebasestorage.app',
    measurementId: 'G-STQTM7FF9B',
  );
}
